mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
server:
  port: 8080

spring:
  profiles:
    active: prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: tt314951
    url: jdbc:mysql://database-1.cxyil04tfi8v.ap-northeast-2.rds.amazonaws.com:3306/leader?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      enabled: false

 
